### ISSUE TITLE
interface conversion: interface is nil, not gosnowflake.SnowflakeRows

### ISSUE THREAD

**Issue by kevin-lindsay-1** [snowflakedb/gosnowflake#940]
When running queries, sometimes I will get the following panic:
```
panic: interface conversion: interface is nil, not gosnowflake.SnowflakeRows
```

Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of GO driver are you using?
1.6.25
   
2. What operating system and processor architecture are you using?
linux-amd64
alpine 3.18.4
   
3. What version of GO are you using?
run `go version` in your console
1.21.3

4.Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();
```
5. What did you do?
- Ran a statement.Query for `show streams`, was successful
- Created a `query` (string)
- Query text was `select "name" from table(result_scan())`
- Ran `db.Prepare(query)` to produce a `sql.Stmt`
- Ran `statement.Query()`
- Got a panic

Here is the panic stacktrace
```log
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:920
runtime.assertI2I
	/usr/local/go/src/runtime/iface.go:425
github.com/snowflakedb/gosnowflake.(*snowflakeStmt).QueryContext
	/usr/root/function/vendor/github.com/snowflakedb/gosnowflake/statement.go:43
database/sql.ctxDriverStmtQuery
	/usr/local/go/src/database/sql/ctxutil.go:82
database/sql.rowsiFromStatement
	/usr/local/go/src/database/sql/sql.go:2808
database/sql.(*Stmt).QueryContext.func1
	/usr/local/go/src/database/sql/sql.go:2758
database/sql.(*DB).retry
	/usr/local/go/src/database/sql/sql.go:1538
database/sql.(*Stmt).QueryContext
	/usr/local/go/src/database/sql/sql.go:2752
database/sql.(*Stmt).Query
	/usr/local/go/src/database/sql/sql.go:2798
```

7. What did you expect to see?

Ideally, I should see the names of the streams being shown.
Less than ideally, I should be given an error, not a panic.

8. Can you set logging to DEBUG and collect the logs?

   https://community.snowflake.com/s/article/How-to-generate-log-file-on-Snowflake-connectors
   
9. What is your Snowflake account identifier, if any? (Optional)

**Comment by kevin-lindsay-1** [comment]
I'm closing this issue because upon further inspection I was on go 1.21.0, not 1.21.3. After updating, it appears this panic is now error handled.

**Comment by kevin-lindsay-1** [comment]
Nevermind, this happened on another query with the exact same stack trace. Seems like some queries result in errors, and sometimes they seem to panic if the query errors?

**Comment by kevin-lindsay-1** [comment]
Here's a few query IDs:
`01afd8da-0403-e416-0044-bc8316450fce`
`01afd8c1-0403-e416-0044-bc831644ae7a`
`01afd8b1-0403-e3f5-0044-bc83164488ce`

These all seem to have error messages in the snowflake UI but cause a panic rather than an error.

**Comment by sfc-gh-dszmolka** [comment]
thank you, all three of them seem to fail with 'normal' errors like compilation error and such, which should indeed not panic the Snowflake Go driver. indeed reproduces with go1.21.3 as well.

also reproduced the issue thanks to your examples, appreciated !

we're going to take a look, but in the meantime I also noticed that if instead of 
```go
stmt, err := db.Prepare(queryBad)
rows, errr := stmt.Query()
```
(which reproduces the issue) i'm using
```go
rows, err := db.Query(queryBad)
```

(as seen e.g. in the [select1.go](https://github.com/snowflakedb/gosnowflake/blob/master/cmd/select1/select1.go#L41-L43) example, or even with cancel context like in [selectmany.go](https://github.com/snowflakedb/gosnowflake/blob/master/cmd/selectmany/selectmany.go#L55) so directly executing without preparing it first) 

then the Go driver doesn't bail out with panic, just nicely returns the expected error from Snowflake. maybe it can help as a workaround, while we're looking into this one.

**Comment by kevin-lindsay-1** [comment]
@sfc-gh-dszmolka I appreciate the workaround.

**Comment by sfc-gh-dszmolka** [comment]
PR #953 should address this; we aim to merge it very soon and release the patched `gosnowflake` driver in the coming days

**Comment by sfc-gh-dszmolka** [comment]
gosnowflake 1.7.0 released with the fix, thank you all for bearing with us !

**Comment by sfc-gh-pfus** [comment]
Hi @kevin-lindsay-1 ! There was a bug in the fix, but it should work in version 1.7.1.
